### ISSUE TITLE
Missing Modules when installing via pip and GitHub

### ISSUE THREAD

**Issue by Tianmaru** [OpenFAST/openfast_toolbox#13]
How to replicate:

```prompt
$ pip install git+https://github.com/OpenFAST/openfast_toolbox.git@648de5b803d60ca22d78d7b392d0f34222c26cac#egg=openfast_toolbox
python 
$ python -c "import openfast_toolbox"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/miniconda3/envs/openfast_toolbox/lib/python3.12/site-packages/openfast_toolbox/__init__.py", line 5, in <module>
    from .io import read
ModuleNotFoundError: No module named 'openfast_toolbox.io'
```

The openfast site-packages directory also only contains `common.py` and `__init__.py`.

**Comment by ebranlard** [comment]
might be fixed by #25

**Comment by coskunkut** [comment]
Until #25 gets merged, using `--use-pep517` fixed the issue for me:

`python -m pip install --use-pep517 -e .`
